# Generated by Django 6.0.1 on 2026-01-25 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_summary_enabled', models.BooleanField(default=True)),
                ('daily_summary_hour', models.IntegerField(default=9, help_text='Hora del dia (0-23)')),
                ('price_drop_enabled', models.BooleanField(default=True)),
                ('price_drop_threshold', models.IntegerField(default=5, help_text='Porcentaje minimo de bajada para alertar')),
                ('new_leads_enabled', models.BooleanField(default=True)),
                ('new_leads_min_score', models.IntegerField(default=0, help_text='Score minimo del lead para alertar (0-100)')),
                ('error_alerts_enabled', models.BooleanField(default=False)),
                ('task_reminders_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Preferences',
                'verbose_name_plural': 'Alert Preferences',
                'db_table': 'notifications_alert_preferences',
            },
        ),
    ]
