"""
Zonas geográficas para Habitaclia (Casa Teva tenant 1 + Find&Look tenant 2).

Módulo neutro: NO depende de camoufox/botasaurus/scrapling.
"""

ZONAS_GEOGRAFICAS = {
    'tarragona_provincia': {'nombre': 'Tarragona Provincia', 'url_slug': 'tarragona', 'is_province': True},
    'lleida_provincia': {'nombre': 'Lleida Provincia', 'url_slug': 'lleida', 'is_province': True},
    'tarragones': {'nombre': 'Tarragonès', 'composite': ['tarragona', 'torredembarra', 'altafulla', 'constantí', 'el_morell']},
    'baix_camp': {'nombre': 'Baix Camp', 'composite': ['reus', 'cambrils', 'salou', 'vila-seca', 'mont-roig_del_camp', 'riudoms']},
    'alt_camp': {'nombre': 'Alt Camp', 'composite': ['valls', 'alcover']},
    'conca_barbera': {'nombre': 'Conca de Barberà', 'composite': ['montblanc', 'l_espluga_de_francolí', 'santa_coloma_de_queralt']},
    'baix_penedes': {'nombre': 'Baix Penedès', 'composite': ['el_vendrell', 'calafell', 'cunit']},
    'baix_ebre': {'nombre': 'Baix Ebre', 'composite': ['tortosa', 'deltebre', 'l_ametlla_de_mar']},
    'montsia': {'nombre': 'Montsià', 'composite': ['amposta', 'sant_carles_de_la_rapita', 'alcanar', 'ulldecona']},
    'priorat': {'nombre': 'Priorat', 'composite': ['falset']},
    'costa_daurada': {'nombre': 'Costa Daurada', 'composite': ['salou', 'cambrils', 'tarragona', 'torredembarra', 'altafulla', 'calafell', 'el_vendrell', 'miami_platja']},
    'segria': {'nombre': 'Segrià', 'composite': ['lleida', 'alcarras', 'almacelles', 'alpicat']},
    'noguera': {'nombre': 'Noguera', 'composite': ['balaguer', 'artesa_de_segre', 'ponts']},
    'pla_urgell': {'nombre': "Pla d'Urgell", 'composite': ['mollerussa', 'bellpuig', 'linyola']},
    'urgell': {'nombre': 'Urgell', 'composite': ['tarrega', 'agramunt']},
    'garrigues': {'nombre': 'Les Garrigues', 'composite': ['les_borges_blanques', 'juneda']},
    'tarragona': {'nombre': 'Tarragona', 'url_slug': 'tarragona'},
    'salou': {'nombre': 'Salou', 'url_slug': 'salou'},
    'cambrils': {'nombre': 'Cambrils', 'url_slug': 'cambrils'},
    'reus': {'nombre': 'Reus', 'url_slug': 'reus'},
    'calafell': {'nombre': 'Calafell', 'url_slug': 'calafell'},
    'torredembarra': {'nombre': 'Torredembarra', 'url_slug': 'torredembarra'},
    'vendrell': {'nombre': 'El Vendrell', 'url_slug': 'el_vendrell'},
    'el_vendrell': {'nombre': 'El Vendrell', 'url_slug': 'el_vendrell'},
    'valls': {'nombre': 'Valls', 'url_slug': 'valls'},
    'tortosa': {'nombre': 'Tortosa', 'url_slug': 'tortosa'},
    'amposta': {'nombre': 'Amposta', 'url_slug': 'amposta'},
    'montblanc': {'nombre': 'Montblanc', 'url_slug': 'montblanc'},
    'altafulla': {'nombre': 'Altafulla', 'url_slug': 'altafulla'},
    'vila-seca': {'nombre': 'Vila-seca', 'url_slug': 'vila-seca'},
    'mont-roig_del_camp': {'nombre': 'Mont-roig del Camp', 'url_slug': 'mont-roig_del_camp'},
    'miami_platja': {'nombre': 'Miami Platja', 'url_slug': 'miami_platja'},
    'riudoms': {'nombre': 'Riudoms', 'url_slug': 'riudoms'},
    'alcover': {'nombre': 'Alcover', 'url_slug': 'alcover'},
    'constantí': {'nombre': 'Constantí', 'url_slug': 'constanti'},
    'el_morell': {'nombre': 'El Morell', 'url_slug': 'el_morell'},
    'cunit': {'nombre': 'Cunit', 'url_slug': 'cunit'},
    'deltebre': {'nombre': 'Deltebre', 'url_slug': 'deltebre'},
    'l_ametlla_de_mar': {'nombre': "L'Ametlla de Mar", 'url_slug': 'l_ametlla_de_mar'},
    'sant_carles_de_la_rapita': {'nombre': 'Sant Carles de la Ràpita', 'url_slug': 'sant_carles_de_la_rapita'},
    'alcanar': {'nombre': 'Alcanar', 'url_slug': 'alcanar'},
    'ulldecona': {'nombre': 'Ulldecona', 'url_slug': 'ulldecona'},
    'falset': {'nombre': 'Falset', 'url_slug': 'falset'},
    'l_espluga_de_francolí': {'nombre': "L'Espluga de Francolí", 'url_slug': 'l_espluga_de_francoli'},
    'santa_coloma_de_queralt': {'nombre': 'Santa Coloma de Queralt', 'url_slug': 'santa_coloma_de_queralt'},
    'lleida': {'nombre': 'Lleida', 'url_slug': 'lleida'},
    'balaguer': {'nombre': 'Balaguer', 'url_slug': 'balaguer'},
    'mollerussa': {'nombre': 'Mollerussa', 'url_slug': 'mollerussa'},
    'tremp': {'nombre': 'Tremp', 'url_slug': 'tremp'},
    'tarrega': {'nombre': 'Tàrrega', 'url_slug': 'tarrega'},
    'alcarras': {'nombre': 'Alcarràs', 'url_slug': 'alcarras'},
    'almacelles': {'nombre': 'Almacelles', 'url_slug': 'almacelles'},
    'alpicat': {'nombre': 'Alpicat', 'url_slug': 'alpicat'},
    'torrefarrera': {'nombre': 'Torrefarrera', 'url_slug': 'torrefarrera'},
    'alcoletge': {'nombre': 'Alcoletge', 'url_slug': 'alcoletge'},
    'rossello': {'nombre': 'Rosselló', 'url_slug': 'rossello'},
    'artesa_de_segre': {'nombre': 'Artesa de Segre', 'url_slug': 'artesa_de_segre'},
    'ponts': {'nombre': 'Ponts', 'url_slug': 'ponts'},
    'bellpuig': {'nombre': 'Bellpuig', 'url_slug': 'bellpuig'},
    'linyola': {'nombre': 'Linyola', 'url_slug': 'linyola'},
    'agramunt': {'nombre': 'Agramunt', 'url_slug': 'agramunt'},
    'les_borges_blanques': {'nombre': 'Les Borges Blanques', 'url_slug': 'les_borges_blanques'},
    'juneda': {'nombre': 'Juneda', 'url_slug': 'juneda'},
    'hospitalet_infant': {'nombre': "L'Hospitalet de l'Infant", 'url_slug': 'l_hospitalet_de_l_infant'},
    'coma_ruga': {'nombre': 'Coma-ruga', 'url_slug': 'coma-ruga'},
    'la_pineda': {'nombre': 'La Pineda', 'url_slug': 'la_pineda'},
    'montroig_camp': {'nombre': 'Mont-roig del Camp', 'url_slug': 'mont-roig_del_camp'},
    'vila_seca': {'nombre': 'Vila-seca', 'url_slug': 'vila-seca'},
    'ametlla_mar': {'nombre': "L'Ametlla de Mar", 'url_slug': 'l_ametlla_de_mar'},
    'sant_carles_rapita': {'nombre': 'Sant Carles de la Ràpita', 'url_slug': 'sant_carles_de_la_rapita'},

    # === Pueblos <=20km de Lleida (radio Segrià) ===
    'albatarrec': {'nombre': 'Albatàrrec', 'url_slug': 'albatarrec'},
    'torre_serona': {'nombre': 'Torre-serona', 'url_slug': 'torre_serona'},
    'montoliu_de_lleida': {'nombre': 'Montoliu de Lleida', 'url_slug': 'montoliu_de_lleida'},
    'sudanell': {'nombre': 'Sudanell', 'url_slug': 'sudanell'},
    'benavent_de_segria': {'nombre': 'Benavent de Segrià', 'url_slug': 'benavent_de_segria'},
    'artesa_de_lleida': {'nombre': 'Artesa de Lleida', 'url_slug': 'artesa_de_lleida'},
    'corbins': {'nombre': 'Corbins', 'url_slug': 'corbins'},
    'vilanova_de_segria': {'nombre': 'Vilanova de Segrià', 'url_slug': 'vilanova_de_segria'},
    'alfes': {'nombre': 'Alfés', 'url_slug': 'alfes'},
    'sunyer': {'nombre': 'Sunyer', 'url_slug': 'sunyer'},
    'vilanova_de_la_barca': {'nombre': 'Vilanova de la Barca', 'url_slug': 'vilanova_de_la_barca'},
    'puigverd_de_lleida': {'nombre': 'Puigverd de Lleida', 'url_slug': 'puigverd_de_lleida'},
    'torres_de_segre': {'nombre': 'Torres de Segre', 'url_slug': 'torres_de_segre'},
    'alguaire': {'nombre': 'Alguaire', 'url_slug': 'alguaire'},
    'aspa': {'nombre': 'Aspa', 'url_slug': 'aspa'},
    'soses': {'nombre': 'Soses', 'url_slug': 'soses'},
    'menarguens': {'nombre': 'Menàrguens', 'url_slug': 'menarguens'},
    'bellvis': {'nombre': 'Bellvís', 'url_slug': 'bellvis'},
    'sidamon': {'nombre': 'Sidamon', 'url_slug': 'sidamon'},
    'sarroca_de_lleida': {'nombre': 'Sarroca de Lleida', 'url_slug': 'sarroca_de_lleida'},
    'aitona': {'nombre': 'Aitona', 'url_slug': 'aitona'},
    'gimenells': {'nombre': 'Gimenells', 'url_slug': 'gimenells_i_el_pla_de_la_font'},
    'fondarella': {'nombre': 'Fondarella', 'url_slug': 'fondarella'},
    'torrebesses': {'nombre': 'Torrebesses', 'url_slug': 'torrebesses'},
    'miralcamp': {'nombre': 'Miralcamp', 'url_slug': 'miralcamp'},
    'vallfogona_balaguer': {'nombre': 'Vallfogona de Balaguer', 'url_slug': 'vallfogona_de_balaguer'},
    'la_canonja': {'nombre': 'La Canonja', 'url_slug': 'la_canonja'},

    'chamartin': {'nombre': 'Chamartín', 'url_slug': 'distrito_chamartin-madrid'},
    'hortaleza': {'nombre': 'Hortaleza', 'url_slug': 'distrito_hortaleza-madrid'},
}
