"""
Zonas geográficas para Milanuncios (Casa Teva tenant 1 + Find&Look tenant 2).

Módulo neutro: NO depende de camoufox/botasaurus/scrapling.
"""

ZONAS_GEOGRAFICAS = {
    'lleida': {'nombre': 'Lleida Ciudad', 'url_path': 'pisos-en-lleida-lleida/'},
    'balaguer': {'nombre': 'Balaguer', 'url_path': 'pisos-en-balaguer-lleida/'},
    'mollerussa': {'nombre': 'Mollerussa', 'url_path': 'pisos-en-mollerussa-lleida/'},
    'les_borges_blanques': {'nombre': 'Les Borges Blanques', 'url_path': 'pisos-en-les-borges-blanques-lleida/'},
    'tremp': {'nombre': 'Tremp', 'url_path': 'pisos-en-tremp-lleida/'},
    'tarrega': {'nombre': 'Tàrrega', 'url_path': 'pisos-en-tarrega-lleida/'},
    'alpicat': {'nombre': 'Alpicat', 'url_path': 'pisos-en-alpicat-lleida/'},
    'alcarras': {'nombre': 'Alcarràs', 'url_path': 'pisos-en-alcarras-lleida/'},
    'torrefarrera': {'nombre': 'Torrefarrera', 'url_path': 'pisos-en-torrefarrera-lleida/'},
    'tarragona': {'nombre': 'Tarragona', 'url_path': 'pisos-en-tarragona-tarragona/'},
    'tarragona_ciudad': {'nombre': 'Tarragona Ciudad', 'url_path': 'pisos-en-tarragona-tarragona/'},
    'salou': {'nombre': 'Salou', 'url_path': 'pisos-en-salou-tarragona/'},
    'cambrils': {'nombre': 'Cambrils', 'url_path': 'pisos-en-cambrils-tarragona/'},
    'reus': {'nombre': 'Reus', 'url_path': 'pisos-en-reus-tarragona/'},
    'vendrell': {'nombre': 'El Vendrell', 'url_path': 'pisos-en-el-vendrell-tarragona/'},
    'altafulla': {'nombre': 'Altafulla', 'url_path': 'pisos-en-altafulla-tarragona/'},
    'torredembarra': {'nombre': 'Torredembarra', 'url_path': 'pisos-en-torredembarra-tarragona/'},
    'calafell': {'nombre': 'Calafell', 'url_path': 'pisos-en-calafell-tarragona/'},
    'la_pineda': {'nombre': 'La Pineda', 'url_path': 'pisos-en-la-pineda-tarragona/'},
    'miami_platja': {'nombre': 'Miami Platja', 'url_path': 'pisos-en-miami-platja-tarragona/'},
    'valls': {'nombre': 'Valls', 'url_path': 'pisos-en-valls-tarragona/'},
    'montblanc': {'nombre': 'Montblanc', 'url_path': 'pisos-en-montblanc-tarragona/'},
    'vila_seca': {'nombre': 'Vila-seca', 'url_path': 'pisos-en-vila-seca-tarragona/'},
    'ametlla_mar': {'nombre': "L'Ametlla de Mar", 'url_path': 'pisos-en-l-ametlla-de-mar-tarragona/'},
    'tortosa': {'nombre': 'Tortosa', 'url_path': 'pisos-en-tortosa-tarragona/'},
    'amposta': {'nombre': 'Amposta', 'url_path': 'pisos-en-amposta-tarragona/'},
    'deltebre': {'nombre': 'Deltebre', 'url_path': 'pisos-en-deltebre-tarragona/'},

    # === Pueblos <=20km de Lleida (radio Segrià) ===
    'albatarrec': {'nombre': 'Albatàrrec', 'url_path': 'pisos-en-albatarrec-lleida/'},
    'torre_serona': {'nombre': 'Torre-serona', 'url_path': 'pisos-en-torre-serona-lleida/'},
    'montoliu_de_lleida': {'nombre': 'Montoliu de Lleida', 'url_path': 'pisos-en-montoliu-de-lleida-lleida/'},
    'alcoletge': {'nombre': 'Alcoletge', 'url_path': 'pisos-en-alcoletge-lleida/'},
    'sudanell': {'nombre': 'Sudanell', 'url_path': 'pisos-en-sudanell-lleida/'},
    'benavent_de_segria': {'nombre': 'Benavent de Segrià', 'url_path': 'pisos-en-benavent-de-segria-lleida/'},
    'rossello': {'nombre': 'Rosselló', 'url_path': 'pisos-en-rossello-lleida/'},
    'els_alamus': {'nombre': 'Els Alamús', 'url_path': 'pisos-en-els-alamus-lleida/'},
    'artesa_de_lleida': {'nombre': 'Artesa de Lleida', 'url_path': 'pisos-en-artesa-de-lleida-lleida/'},
    'corbins': {'nombre': 'Corbins', 'url_path': 'pisos-en-corbins-lleida/'},
    'vilanova_de_segria': {'nombre': 'Vilanova de Segrià', 'url_path': 'pisos-en-vilanova-de-segria-lleida/'},
    'alfes': {'nombre': 'Alfés', 'url_path': 'pisos-en-alfes-lleida/'},
    'sunyer': {'nombre': 'Sunyer', 'url_path': 'pisos-en-sunyer-lleida/'},
    'vilanova_de_la_barca': {'nombre': 'Vilanova de la Barca', 'url_path': 'pisos-en-vilanova-de-la-barca-lleida/'},
    'puigverd_de_lleida': {'nombre': 'Puigverd de Lleida', 'url_path': 'pisos-en-puigverd-de-lleida-lleida/'},
    'torres_de_segre': {'nombre': 'Torres de Segre', 'url_path': 'pisos-en-torres-de-segre-lleida/'},
    'alguaire': {'nombre': 'Alguaire', 'url_path': 'pisos-en-alguaire-lleida/'},
    'la_portella': {'nombre': 'La Portella', 'url_path': 'pisos-en-la-portella-lleida/'},
    'aspa': {'nombre': 'Aspa', 'url_path': 'pisos-en-aspa-lleida/'},
    'soses': {'nombre': 'Soses', 'url_path': 'pisos-en-soses-lleida/'},
    'menarguens': {'nombre': 'Menàrguens', 'url_path': 'pisos-en-menarguens-lleida/'},
    'bellvis': {'nombre': 'Bellvís', 'url_path': 'pisos-en-bellvis-lleida/'},
    'sidamon': {'nombre': 'Sidamon', 'url_path': 'pisos-en-sidamon-lleida/'},
    'sarroca_de_lleida': {'nombre': 'Sarroca de Lleida', 'url_path': 'pisos-en-sarroca-de-lleida-lleida/'},
    'aitona': {'nombre': 'Aitona', 'url_path': 'pisos-en-aitona-lleida/'},
    'gimenells': {'nombre': 'Gimenells', 'url_path': 'pisos-en-gimenells-lleida/'},
    'fondarella': {'nombre': 'Fondarella', 'url_path': 'pisos-en-fondarella-lleida/'},
    'torrebesses': {'nombre': 'Torrebesses', 'url_path': 'pisos-en-torrebesses-lleida/'},
    'miralcamp': {'nombre': 'Miralcamp', 'url_path': 'pisos-en-miralcamp-lleida/'},
    'palau_anglesola': {'nombre': 'El Palau d\'Anglesola', 'url_path': 'pisos-en-el-palau-d-anglesola-lleida/'},
    'vallfogona_balaguer': {'nombre': 'Vallfogona de Balaguer', 'url_path': 'pisos-en-vallfogona-de-balaguer-lleida/'},

    'chamartin': {'nombre': 'Chamartín', 'url_path': 'pisos-en-madrid-madrid/'},
    'hortaleza': {'nombre': 'Hortaleza', 'url_path': 'pisos-en-madrid-madrid/'},
}
