casa_teva:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASSWORD', '') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'casa_teva_db') }}"
      schema: public
      threads: 4
      connect_timeout: 30
      search_path: public,raw,staging,marts,analytics
      sslmode: require
