casa_teva:
  target: prod
  outputs:
    prod:
      type: postgres
      host: inmoleads-db.postgres.database.azure.com
      port: 5432
      user: inmoleadsadmin
      password: "ataulfo1!"
      dbname: inmoleadsdb
      schema: public
      threads: 4
      connect_timeout: 30
      search_path: public,raw,staging,marts,analytics
      sslmode: require
