# Generated by Django 6.0.1 on 2026-01-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_add_comercial_fields_to_tenantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar la key', max_length=100)),
                ('key_hash', models.CharField(help_text='SHA256 hash de la API key', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='Prefijo visible de la key (para identificacion)', max_length=8)),
                ('can_read_leads', models.BooleanField(default=True)),
                ('can_write_leads', models.BooleanField(default=True)),
                ('can_manage_webhooks', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=0)),
                ('rate_limit_per_hour', models.IntegerField(default=100, help_text='Requests permitidos por hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Si es null, no expira', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.tenant')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL donde se enviaran los eventos', max_length=500)),
                ('event_type', models.CharField(choices=[('new_lead', 'Nuevo Lead'), ('status_change', 'Cambio de Estado'), ('price_drop', 'Bajada de Precio')], max_length=20)),
                ('secret', models.CharField(help_text='Secret para firma HMAC-SHA256', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('max_failures', models.IntegerField(default=5, help_text='Desactivar tras N fallos consecutivos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'api_webhooks',
                'unique_together': {('tenant', 'url', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api_v1.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'db_table': 'api_webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
