# Generated by Django 5.1 on 2025-12-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorUsuarioPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=50)),
                ('usuario_id', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('num_anuncios', models.IntegerField(default=0)),
                ('ultimo_anuncio_url', models.TextField(blank=True)),
                ('primera_deteccion', models.DateTimeField(auto_now_add=True)),
                ('ultima_deteccion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador Usuario Portal',
                'verbose_name_plural': 'Contadores Usuarios Portal',
                'db_table': 'contador_usuarios_portal',
                'unique_together': {('portal', 'usuario_id')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('wallapop', 'Wallapop'), ('milanuncios', 'Milanuncios'), ('fotocasa', 'Fotocasa')], max_length=50)),
                ('usuario_id', models.CharField(help_text='ID del usuario en el portal', max_length=255)),
                ('nombre_usuario', models.CharField(help_text='Nombre mostrado en el portal', max_length=255)),
                ('motivo', models.CharField(choices=[('manual', 'Añadido manualmente'), ('automatico', 'Detectado automáticamente (múltiples anuncios)'), ('reportado', 'Reportado por usuario')], default='manual', max_length=20)),
                ('num_anuncios_detectados', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Si es null, aplica a todos los tenants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_blacklist', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Usuario Blacklist',
                'verbose_name_plural': 'Usuarios Blacklist',
                'db_table': 'usuarios_blacklist',
                'unique_together': {('portal', 'usuario_id', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la zona', max_length=255)),
                ('slug', models.SlugField(help_text='Identificador único de la zona', max_length=100)),
                ('tipo', models.CharField(choices=[('preestablecida', 'Zona Preestablecida'), ('personalizada', 'Zona Personalizada')], default='preestablecida', max_length=20)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radio_km', models.IntegerField(default=20, help_text='Radio de búsqueda en kilómetros')),
                ('provincia_id', models.IntegerField(blank=True, help_text='ID de provincia para Milanuncios', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('precio_minimo', models.IntegerField(default=5000, help_text='Precio mínimo para filtrar alquileres')),
                ('scrapear_milanuncios', models.BooleanField(default=True)),
                ('scrapear_fotocasa', models.BooleanField(default=True)),
                ('scrapear_wallapop', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Zona Geográfica',
                'verbose_name_plural': 'Zonas Geográficas',
                'db_table': 'zonas_geograficas',
                'ordering': ['tenant', 'nombre'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
