# Generated by Django 5.2.9 on 2025-12-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_zonas_blacklist_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonageografica',
            name='scrapear_pisos',
            field=models.BooleanField(default=True),
        ),
    ]
