# Generated by Django 5.2.9 on 2025-12-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_scrapear_pisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('milanuncios', 'Milanuncios'), ('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('pisos', 'Pisos.com'), ('all', 'Todos los portales')], max_length=50)),
                ('zona_nombre', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('leads_encontrados', models.IntegerField(default=0)),
                ('leads_guardados', models.IntegerField(default=0)),
                ('leads_filtrados', models.IntegerField(default=0)),
                ('leads_duplicados', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to='core.tenant')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to='core.zonageografica')),
            ],
            options={
                'verbose_name': 'Trabajo de Scraping',
                'verbose_name_plural': 'Trabajos de Scraping',
                'db_table': 'scraping_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
