# Generated by Django 5.2.9 on 2026-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pisos_wallapop_add_idealista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingjob',
            name='portal',
            field=models.CharField(choices=[('milanuncios', 'Milanuncios'), ('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('idealista', 'Idealista'), ('all', 'Todos los portales')], max_length=50),
        ),
    ]
