# Generated by Django 6.0.1 on 2026-01-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_idealista_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='comercial_email',
            field=models.EmailField(blank=True, help_text='Email para recibir respuestas de leads', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='comercial_nombre',
            field=models.CharField(blank=True, help_text='Nombre que aparece en formularios de contacto', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='comercial_telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto en formularios', max_length=20),
        ),
    ]
