# Generated by Django 6.0.1 on 2026-01-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_comercial_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='comercial_email',
            field=models.EmailField(blank=True, help_text='Email para recibir respuestas (si vacío, usa user.email)', max_length=254),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='comercial_nombre',
            field=models.CharField(blank=True, help_text='Nombre en formularios (si vacío, usa user.first_name)', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='comercial_telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto en formularios', max_length=20),
        ),
    ]
