# Generated by Django 5.1 on 2026-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_re_add_scrapear_wallapop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingjob',
            name='portal',
            field=models.CharField(choices=[('milanuncios', 'Milanuncios'), ('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('idealista', 'Idealista'), ('wallapop', 'Wallapop'), ('all', 'Todos los portales')], max_length=50),
        ),
    ]
