version: 2

models:
  - name: stg_fotocasa
    description: "Staging model for Fotocasa listings"
    columns:
      - name: raw_listing_id
        description: "ID from raw.raw_listings table"
        tests:
          - not_null
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
      - name: telefono_norm
        description: "Normalized phone number (optional)"
      - name: precio
        description: "Property price in EUR"
      - name: fotos
        description: "Array of photo URLs"

  - name: stg_habitaclia
    description: "Staging model for Habitaclia listings"
    columns:
      - name: raw_listing_id
        description: "ID from raw.raw_listings table"
        tests:
          - not_null
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
      - name: telefono_norm
        description: "Normalized phone number (optional)"
      - name: precio
        description: "Property price in EUR"
      - name: fotos
        description: "Array of photo URLs"

  - name: stg_milanuncios
    description: "Staging model for Milanuncios listings"
    columns:
      - name: raw_listing_id
        description: "ID from raw.raw_listings table"
        tests:
          - not_null
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
      - name: telefono_norm
        description: "Normalized phone number (optional)"
      - name: precio
        description: "Property price in EUR"
      - name: fotos
        description: "Array of photo URLs"

  - name: stg_idealista
    description: "Staging model for Idealista listings"
    columns:
      - name: raw_listing_id
        description: "ID from raw.raw_listings table"
        tests:
          - not_null
      - name: tenant_id
        description: "Tenant identifier"
        tests:
          - not_null
      - name: telefono_norm
        description: "Normalized phone number (optional)"
      - name: precio
        description: "Property price in EUR"
      - name: fotos
        description: "Array of photo URLs"
