# Generated by Django 5.2.9 on 2025-12-20 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_zonas_blacklist_models'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEstado',
            fields=[
                ('lead_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('telefono_norm', models.CharField(db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En proceso'), ('CONTACTADO_SIN_RESPUESTA', 'Contactado sin respuesta'), ('INTERESADO', 'Interesado'), ('NO_INTERESADO', 'No interesado'), ('EN_ESPERA', 'En espera'), ('NO_CONTACTAR', 'No contactar'), ('CLIENTE', 'Cliente'), ('YA_VENDIDO', 'Ya vendido')], default='NUEVO', max_length=30)),
                ('numero_intentos', models.IntegerField(default=0)),
                ('fecha_primer_contacto', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_estado_asignados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_estados', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Estado de Lead',
                'verbose_name_plural': 'Estados de Leads',
                'db_table': 'leads_lead_estado',
                'unique_together': {('tenant', 'telefono_norm')},
            },
        ),
    ]
