# Generated by Django 5.1 on 2025-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_norm', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('direccion', models.TextField()),
                ('zona_geografica', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fotos', models.JSONField(default=list)),
                ('portal', models.CharField(max_length=50)),
                ('url_anuncio', models.TextField()),
                ('data_lake_reference', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En proceso'), ('CONTACTADO_SIN_RESPUESTA', 'Contactado sin respuesta'), ('INTERESADO', 'Interesado'), ('NO_INTERESADO', 'No interesado'), ('NO_CONTACTAR', 'No contactar'), ('CLIENTE', 'Cliente'), ('YA_VENDIDO', 'Ya vendido')], default='NUEVO', max_length=30)),
                ('numero_intentos', models.IntegerField(default=0)),
                ('fecha_scraping', models.DateTimeField()),
                ('fecha_primer_contacto', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'marts"."dim_leads',
                'ordering': ['-fecha_scraping'],
                'managed': False,
            },
        ),
    ]
