# Generated by Django 5.2.9 on 2025-12-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_lead_estado_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadestado',
            unique_together=set(),
        ),
    ]
