# Generated by Django 5.2.9 on 2025-12-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_scrapear_pisos'),
        ('leads', '0003_remove_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('milanuncios', 'Milanuncios'), ('wallapop', 'Wallapop'), ('fotocasa', 'Fotocasa'), ('pisos', 'Pisos.com')], max_length=50)),
                ('anuncio_id', models.CharField(help_text='ID unico del anuncio en el portal', max_length=255)),
                ('url_anuncio', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo por el que se añadio a blacklist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_blacklist_creados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_blacklist', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Anuncio en Blacklist',
                'verbose_name_plural': 'Anuncios en Blacklist',
                'db_table': 'leads_anuncio_blacklist',
                'indexes': [models.Index(fields=['portal', 'anuncio_id'], name='leads_anunc_portal_1a65dd_idx')],
                'unique_together': {('tenant', 'portal', 'anuncio_id')},
            },
        ),
    ]
