# Generated by Django 6.0.1 on 2026-01-17 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_idealista_portal'),
        ('leads', '0006_contact_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('milanuncios', 'Milanuncios'), ('idealista', 'Idealista')], max_length=50)),
                ('email', models.EmailField(help_text='Email de la cuenta del portal', max_length=254)),
                ('password_encrypted', models.TextField(help_text='Password cifrada con Fernet')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Portal',
                'verbose_name_plural': 'Credenciales de Portales',
                'db_table': 'leads_portal_credential',
            },
        ),
        migrations.RenameIndex(
            model_name='contactqueue',
            new_name='leads_conta_estado_356b03_idx',
            old_name='leads_conta_estado_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='contactqueue',
            new_name='leads_conta_tenant__9116fb_idx',
            old_name='leads_conta_tenant__d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='anuncioblacklist',
            name='portal',
            field=models.CharField(choices=[('milanuncios', 'Milanuncios'), ('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('idealista', 'Idealista')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='lead',
            table='public_marts"."dim_leads',
        ),
        migrations.AddField(
            model_name='portalcredential',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='portalcredential',
            unique_together={('tenant', 'portal')},
        ),
    ]
