# Generated by Django 6.0.1 on 2026-01-19 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_comercial_fields_to_tenantuser'),
        ('leads', '0007_add_portal_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('llamar', 'Llamar'), ('visitar', 'Visitar'), ('enviar_info', 'Enviar información'), ('seguimiento', 'Seguimiento'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='seguimiento', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_asignadas', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_creadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'leads_task',
                'ordering': ['completada', 'fecha_vencimiento', '-prioridad'],
                'indexes': [models.Index(fields=['tenant', 'asignado_a', 'completada'], name='leads_task_tenant__301aa5_idx'), models.Index(fields=['fecha_vencimiento', 'completada'], name='leads_task_fecha_v_4e1d77_idx')],
            },
        ),
    ]
