# Generated by Django 6.0.1 on 2026-02-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_comercial_fields_to_tenantuser'),
        ('leads', '0008_add_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactqueue',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactqueue',
            name='respondio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactqueue',
            name='portal',
            field=models.CharField(choices=[('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('milanuncios', 'Milanuncios'), ('idealista', 'Idealista')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portalsession',
            name='portal',
            field=models.CharField(choices=[('fotocasa', 'Fotocasa'), ('habitaclia', 'Habitaclia'), ('milanuncios', 'Milanuncios'), ('idealista', 'Idealista')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='lead',
            table='"public_marts"."dim_leads"',
        ),
        migrations.CreateModel(
            name='AutoContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
                ('solo_particulares', models.BooleanField(default=True)),
                ('score_minimo', models.IntegerField(default=0)),
                ('precio_minimo', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('precio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contactar_fotocasa', models.BooleanField(default=True)),
                ('contactar_habitaclia', models.BooleanField(default=True)),
                ('contactar_milanuncios', models.BooleanField(default=True)),
                ('contactar_idealista', models.BooleanField(default=True)),
                ('max_contactos_dia', models.IntegerField(default=5)),
                ('max_contactos_portal_dia', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_contact_config', to='core.tenant')),
            ],
            options={
                'db_table': 'leads_auto_contact_config',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('portal', 'Formulario Portal'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='portal', max_length=20)),
                ('asunto', models.CharField(blank=True, help_text='Asunto (para email)', max_length=255)),
                ('cuerpo', models.TextField(help_text='Variables: {nombre_zona}, {tipo_propiedad}, {precio}, {portal}, {url_anuncio}')),
                ('activa', models.BooleanField(default=True)),
                ('peso', models.IntegerField(default=100, help_text='Peso relativo para A/B testing. Mayor peso = mas frecuente.')),
                ('veces_usada', models.IntegerField(default=0)),
                ('veces_respondida', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.tenant')),
            ],
            options={
                'db_table': 'leads_message_template',
                'ordering': ['-peso', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='contactqueue',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='leads.messagetemplate'),
        ),
    ]
