# Generated by Django 5.2.9 on 2026-06-26 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scrapingjob_portal'),
        ('leads', '0009_message_template_auto_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completada', 'fecha_vencimiento'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.CreateModel(
            name='LeadDireccion',
            fields=[
                ('lead_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direccion_exacta', models.CharField(max_length=500)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_direcciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_direcciones', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Direccion de Lead',
                'verbose_name_plural': 'Direcciones de Leads',
                'db_table': 'leads_lead_direccion',
            },
        ),
        migrations.CreateModel(
            name='ContactPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=100)),
                ('tipo', models.CharField(choices=[('en_venta', 'En venta'), ('vendida', 'Vendida')], default='en_venta', max_length=20)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='leads.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_propiedades_creadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_propiedades', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Propiedad de Contacto',
                'verbose_name_plural': 'Propiedades de Contactos',
                'db_table': 'leads_contact_propiedad',
                'ordering': ['-created_at'],
                'unique_together': {('contact', 'lead_id')},
            },
        ),
    ]
