# Generated by Django 5.2.9 on 2026-07-06 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_task_options_leaddireccion_contactpropiedad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('accion', models.CharField(choices=[('estado_creado', 'Estado creado'), ('estado_cambiado', 'Estado cambiado'), ('estado_borrado', 'Estado borrado'), ('lead_borrado', 'Lead borrado'), ('lead_agencia', 'Marcado como agencia (borrado)')], db_index=True, max_length=30)),
                ('lead_id', models.CharField(db_index=True, max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('portal', models.CharField(blank=True, default='', max_length=50)),
                ('titulo', models.TextField(blank=True, default='')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=30)),
                ('detalle', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'db_table': 'leads_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
